{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.lint",
    "module": "lint-gradle",
    "version": "30.1.0-alpha13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "lint-gradle-30.1.0-alpha13.jar",
          "url": "lint-gradle-30.1.0-alpha13.jar",
          "size": 71727,
          "sha512": "15f28930c742f534c64717577a277048c36fd06d8290f95befa25872f2cb620157abd22464bbf7a2a394be447f267ef739ecd17c91a65510ee7dd3f5386f13ed",
          "sha256": "b498361c4c6271d70585527e5c232365b53b23eaeb864fcde6c891bbfaf751b4",
          "sha1": "9d8784b509e30fceddd373764331c7bf3e3e1cd2",
          "md5": "71cf50e603f6dfa684cb11aefe0fdd89"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "30.1.0-alpha13"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "30.1.0-alpha13"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0-alpha13"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder",
          "version": {
            "requires": "7.1.0-alpha13"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "7.1.0-alpha13"
          }
        },
        {
          "group": "com.android.tools.external.com-intellij",
          "module": "intellij-core",
          "version": {
            "requires": "30.1.0-alpha13"
          }
        },
        {
          "group": "com.android.tools.external.com-intellij",
          "module": "kotlin-compiler",
          "version": {
            "requires": "30.1.0-alpha13"
          }
        },
        {
          "group": "com.android.tools.external.org-jetbrains",
          "module": "uast",
          "version": {
            "requires": "30.1.0-alpha13"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "30.1.0-alpha13"
          }
        },
        {
          "group": "com.android.tools.lint",
          "module": "lint",
          "version": {
            "requires": "30.1.0-alpha13"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "7.1.0-alpha13"
          }
        },
        {
          "group": "com.android.tools",
          "module": "repository",
          "version": {
            "requires": "30.1.0-alpha13"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "3.0.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "lint-gradle-30.1.0-alpha13.jar",
          "url": "lint-gradle-30.1.0-alpha13.jar",
          "size": 71727,
          "sha512": "15f28930c742f534c64717577a277048c36fd06d8290f95befa25872f2cb620157abd22464bbf7a2a394be447f267ef739ecd17c91a65510ee7dd3f5386f13ed",
          "sha256": "b498361c4c6271d70585527e5c232365b53b23eaeb864fcde6c891bbfaf751b4",
          "sha1": "9d8784b509e30fceddd373764331c7bf3e3e1cd2",
          "md5": "71cf50e603f6dfa684cb11aefe0fdd89"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lint-gradle-30.1.0-alpha13-javadoc.jar",
          "url": "lint-gradle-30.1.0-alpha13-javadoc.jar",
          "size": 425401,
          "sha512": "61db6fcae4e554bc8305a04cabf256a3ddaf1f820203f2cdd4bc11572cf31ac7da1dce8cb4bd4816afdb2941d9b97e8d94c6d776430c752625bff0cff7a8350f",
          "sha256": "a14c81f7defbe6f0c752deb56e492154c1514f24f384a04a2ee6e865a40dac70",
          "sha1": "594cee1f0851d9017d26c86eaa65941b612b5b11",
          "md5": "73944fa607e4f12e779a79ccab49e1a3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lint-gradle-30.1.0-alpha13-sources.jar",
          "url": "lint-gradle-30.1.0-alpha13-sources.jar",
          "size": 71493,
          "sha512": "9cb69fad753c1034362759748942a3ee2dc5b756e829259fe9814b708a5cfef946109293b8743c507caab78d217232050941f03ca3b6aa4aac99d55db085be8e",
          "sha256": "bdeba5867e073dab5dd0e964252bee1a015c19b37c0257afe6c30201184d04c1",
          "sha1": "38f256bfa03953947f068bd460cbe6954491ae31",
          "md5": "08c53cbb76185d8859f2c4096af4d600"
        }
      ]
    }
  ]
}
